name: clima_app2
description: "Aplicativo de clima feito com Flutter."

# ğŸ”’ Projeto privado (nÃ£o serÃ¡ publicado no pub.dev)
publish_to: "none" # CrÃ©ditos visuais: https://icons8.com.br/

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# ğŸ“¦ DependÃªncias principais
dependencies:
  flutter:
    sdk: flutter

  # ğŸŒ UI e Ã­cones
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  weather_icons: ^3.0.0
  flutter_spinkit: ^5.2.1

  # ğŸŒ LocalizaÃ§Ã£o e clima
  dio: ^5.8.0+1
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # âš™ï¸ Estado e armazenamento
  get: ^4.7.2
  get_storage: ^2.1.1

  # ğŸ” VariÃ¡veis de ambiente
  flutter_dotenv: ^5.2.1

  # ğŸš€ Splash screen personalizada
  flutter_native_splash: ^2.4.6

# âš™ï¸ ConfiguraÃ§Ã£o do splash screen
flutter_native_splash:
  color: "#121212"
  color_dark: "#121212"
  image: assets/splash_logo/logo.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

# ğŸ§ª DependÃªncias de desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0
  mocktail: ^1.0.4
  build_runner: ^2.4.4
  flutter_lints: ^6.0.0
  geolocator_platform_interface: ^4.0.0

# ğŸ¯ ConfiguraÃ§Ãµes do Flutter
flutter:
  uses-material-design: true

  # ğŸ…°ï¸ Fontes personalizadas
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf

  # ğŸ–¼ï¸ DiretÃ³rios de assets
  assets:
    - assets/splash_logo/
    - assets/fonts/